const mock = [
  {
    flag: "https://restcountries.eu/data/afg.svg",
    name: "Afghanistan",
    alpha2Code: "AF",
    capital: "Kabul",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/ala.svg",
    name: "Åland Islands",
    alpha2Code: "AX",
    capital: "Mariehamn",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/alb.svg",
    name: "Albania",
    alpha2Code: "AL",
    capital: "Tirana",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/dza.svg",
    name: "Algeria",
    alpha2Code: "DZ",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/asm.svg",
    name: "American Samoa",
    alpha2Code: "AS",
    capital: "Pago Pago",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/and.svg",
    name: "Andorra",
    alpha2Code: "AD",
    capital: "Andorra la Vella",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/ago.svg",
    name: "Angola",
    alpha2Code: "AO",
    capital: "Luanda",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/aia.svg",
    name: "Anguilla",
    alpha2Code: "AI",
    capital: "The Valley",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/ata.svg",
    name: "Antarctica",
    alpha2Code: "AQ",
    capital: "",
    region: "Polar",
    subregion: "",
  },
  {
    flag: "https://restcountries.eu/data/atg.svg",
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    capital: "Saint John's",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/arg.svg",
    name: "Argentina",
    alpha2Code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/arm.svg",
    name: "Armenia",
    alpha2Code: "AM",
    capital: "Yerevan",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/abw.svg",
    name: "Aruba",
    alpha2Code: "AW",
    capital: "Oranjestad",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/aus.svg",
    name: "Australia",
    alpha2Code: "AU",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/aut.svg",
    name: "Austria",
    alpha2Code: "AT",
    capital: "Vienna",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/aze.svg",
    name: "Azerbaijan",
    alpha2Code: "AZ",
    capital: "Baku",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/bhs.svg",
    name: "Bahamas",
    alpha2Code: "BS",
    capital: "Nassau",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/bhr.svg",
    name: "Bahrain",
    alpha2Code: "BH",
    capital: "Manama",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/bgd.svg",
    name: "Bangladesh",
    alpha2Code: "BD",
    capital: "Dhaka",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/brb.svg",
    name: "Barbados",
    alpha2Code: "BB",
    capital: "Bridgetown",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/blr.svg",
    name: "Belarus",
    alpha2Code: "BY",
    capital: "Minsk",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/bel.svg",
    name: "Belgium",
    alpha2Code: "BE",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/blz.svg",
    name: "Belize",
    alpha2Code: "BZ",
    capital: "Belmopan",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/ben.svg",
    name: "Benin",
    alpha2Code: "BJ",
    capital: "Porto-Novo",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/bmu.svg",
    name: "Bermuda",
    alpha2Code: "BM",
    capital: "Hamilton",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/btn.svg",
    name: "Bhutan",
    alpha2Code: "BT",
    capital: "Thimphu",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/bol.svg",
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    capital: "Sucre",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/bes.svg",
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    capital: "Kralendijk",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/bih.svg",
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    capital: "Sarajevo",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/bwa.svg",
    name: "Botswana",
    alpha2Code: "BW",
    capital: "Gaborone",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/bvt.svg",
    name: "Bouvet Island",
    alpha2Code: "BV",
    capital: "",
    region: "",
    subregion: "",
  },
  {
    flag: "https://restcountries.eu/data/bra.svg",
    name: "Brazil",
    alpha2Code: "BR",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/iot.svg",
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    capital: "Diego Garcia",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/umi.svg",
    name: "United States Minor Outlying Islands",
    alpha2Code: "UM",
    capital: "",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/vgb.svg",
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    capital: "Road Town",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/vir.svg",
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    capital: "Charlotte Amalie",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/brn.svg",
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/bgr.svg",
    name: "Bulgaria",
    alpha2Code: "BG",
    capital: "Sofia",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/bfa.svg",
    name: "Burkina Faso",
    alpha2Code: "BF",
    capital: "Ouagadougou",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/bdi.svg",
    name: "Burundi",
    alpha2Code: "BI",
    capital: "Bujumbura",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/khm.svg",
    name: "Cambodia",
    alpha2Code: "KH",
    capital: "Phnom Penh",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/cmr.svg",
    name: "Cameroon",
    alpha2Code: "CM",
    capital: "Yaoundé",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/can.svg",
    name: "Canada",
    alpha2Code: "CA",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/cpv.svg",
    name: "Cabo Verde",
    alpha2Code: "CV",
    capital: "Praia",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/cym.svg",
    name: "Cayman Islands",
    alpha2Code: "KY",
    capital: "George Town",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/caf.svg",
    name: "Central African Republic",
    alpha2Code: "CF",
    capital: "Bangui",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/tcd.svg",
    name: "Chad",
    alpha2Code: "TD",
    capital: "N'Djamena",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/chl.svg",
    name: "Chile",
    alpha2Code: "CL",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/chn.svg",
    name: "China",
    alpha2Code: "CN",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/cxr.svg",
    name: "Christmas Island",
    alpha2Code: "CX",
    capital: "Flying Fish Cove",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/cck.svg",
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    capital: "West Island",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/col.svg",
    name: "Colombia",
    alpha2Code: "CO",
    capital: "Bogotá",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/com.svg",
    name: "Comoros",
    alpha2Code: "KM",
    capital: "Moroni",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/cog.svg",
    name: "Congo",
    alpha2Code: "CG",
    capital: "Brazzaville",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/cod.svg",
    name: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    capital: "Kinshasa",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/cok.svg",
    name: "Cook Islands",
    alpha2Code: "CK",
    capital: "Avarua",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/cri.svg",
    name: "Costa Rica",
    alpha2Code: "CR",
    capital: "San José",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/hrv.svg",
    name: "Croatia",
    alpha2Code: "HR",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/cub.svg",
    name: "Cuba",
    alpha2Code: "CU",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/cuw.svg",
    name: "Curaçao",
    alpha2Code: "CW",
    capital: "Willemstad",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/cyp.svg",
    name: "Cyprus",
    alpha2Code: "CY",
    capital: "Nicosia",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/cze.svg",
    name: "Czech Republic",
    alpha2Code: "CZ",
    capital: "Prague",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/dnk.svg",
    name: "Denmark",
    alpha2Code: "DK",
    capital: "Copenhagen",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/dji.svg",
    name: "Djibouti",
    alpha2Code: "DJ",
    capital: "Djibouti",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/dma.svg",
    name: "Dominica",
    alpha2Code: "DM",
    capital: "Roseau",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/dom.svg",
    name: "Dominican Republic",
    alpha2Code: "DO",
    capital: "Santo Domingo",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/ecu.svg",
    name: "Ecuador",
    alpha2Code: "EC",
    capital: "Quito",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/egy.svg",
    name: "Egypt",
    alpha2Code: "EG",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/slv.svg",
    name: "El Salvador",
    alpha2Code: "SV",
    capital: "San Salvador",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/gnq.svg",
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    capital: "Malabo",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/eri.svg",
    name: "Eritrea",
    alpha2Code: "ER",
    capital: "Asmara",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/est.svg",
    name: "Estonia",
    alpha2Code: "EE",
    capital: "Tallinn",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/eth.svg",
    name: "Ethiopia",
    alpha2Code: "ET",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/flk.svg",
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    capital: "Stanley",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/fro.svg",
    name: "Faroe Islands",
    alpha2Code: "FO",
    capital: "Tórshavn",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/fji.svg",
    name: "Fiji",
    alpha2Code: "FJ",
    capital: "Suva",
    region: "Oceania",
    subregion: "Melanesia",
  },
  {
    flag: "https://restcountries.eu/data/fin.svg",
    name: "Finland",
    alpha2Code: "FI",
    capital: "Helsinki",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/fra.svg",
    name: "France",
    alpha2Code: "FR",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/guf.svg",
    name: "French Guiana",
    alpha2Code: "GF",
    capital: "Cayenne",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/pyf.svg",
    name: "French Polynesia",
    alpha2Code: "PF",
    capital: "Papeetē",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/atf.svg",
    name: "French Southern Territories",
    alpha2Code: "TF",
    capital: "Port-aux-Français",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/gab.svg",
    name: "Gabon",
    alpha2Code: "GA",
    capital: "Libreville",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/gmb.svg",
    name: "Gambia",
    alpha2Code: "GM",
    capital: "Banjul",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/geo.svg",
    name: "Georgia",
    alpha2Code: "GE",
    capital: "Tbilisi",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/deu.svg",
    name: "Germany",
    alpha2Code: "DE",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/gha.svg",
    name: "Ghana",
    alpha2Code: "GH",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/gib.svg",
    name: "Gibraltar",
    alpha2Code: "GI",
    capital: "Gibraltar",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/grc.svg",
    name: "Greece",
    alpha2Code: "GR",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/grl.svg",
    name: "Greenland",
    alpha2Code: "GL",
    capital: "Nuuk",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/grd.svg",
    name: "Grenada",
    alpha2Code: "GD",
    capital: "St. George's",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/glp.svg",
    name: "Guadeloupe",
    alpha2Code: "GP",
    capital: "Basse-Terre",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/gum.svg",
    name: "Guam",
    alpha2Code: "GU",
    capital: "Hagåtña",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/gtm.svg",
    name: "Guatemala",
    alpha2Code: "GT",
    capital: "Guatemala City",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/ggy.svg",
    name: "Guernsey",
    alpha2Code: "GG",
    capital: "St. Peter Port",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/gin.svg",
    name: "Guinea",
    alpha2Code: "GN",
    capital: "Conakry",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/gnb.svg",
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    capital: "Bissau",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/guy.svg",
    name: "Guyana",
    alpha2Code: "GY",
    capital: "Georgetown",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/hti.svg",
    name: "Haiti",
    alpha2Code: "HT",
    capital: "Port-au-Prince",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/hmd.svg",
    name: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    capital: "",
    region: "",
    subregion: "",
  },
  {
    flag: "https://restcountries.eu/data/vat.svg",
    name: "Holy See",
    alpha2Code: "VA",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/hnd.svg",
    name: "Honduras",
    alpha2Code: "HN",
    capital: "Tegucigalpa",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/hkg.svg",
    name: "Hong Kong",
    alpha2Code: "HK",
    capital: "City of Victoria",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/hun.svg",
    name: "Hungary",
    alpha2Code: "HU",
    capital: "Budapest",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/isl.svg",
    name: "Iceland",
    alpha2Code: "IS",
    capital: "Reykjavík",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/ind.svg",
    name: "India",
    alpha2Code: "IN",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/idn.svg",
    name: "Indonesia",
    alpha2Code: "ID",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/civ.svg",
    name: "Côte d'Ivoire",
    alpha2Code: "CI",
    capital: "Yamoussoukro",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/irn.svg",
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/irq.svg",
    name: "Iraq",
    alpha2Code: "IQ",
    capital: "Baghdad",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/irl.svg",
    name: "Ireland",
    alpha2Code: "IE",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/imn.svg",
    name: "Isle of Man",
    alpha2Code: "IM",
    capital: "Douglas",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/isr.svg",
    name: "Israel",
    alpha2Code: "IL",
    capital: "Jerusalem",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/ita.svg",
    name: "Italy",
    alpha2Code: "IT",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/jam.svg",
    name: "Jamaica",
    alpha2Code: "JM",
    capital: "Kingston",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/jpn.svg",
    name: "Japan",
    alpha2Code: "JP",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/jey.svg",
    name: "Jersey",
    alpha2Code: "JE",
    capital: "Saint Helier",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/jor.svg",
    name: "Jordan",
    alpha2Code: "JO",
    capital: "Amman",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/kaz.svg",
    name: "Kazakhstan",
    alpha2Code: "KZ",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/ken.svg",
    name: "Kenya",
    alpha2Code: "KE",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/kir.svg",
    name: "Kiribati",
    alpha2Code: "KI",
    capital: "South Tarawa",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/kwt.svg",
    name: "Kuwait",
    alpha2Code: "KW",
    capital: "Kuwait City",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/kgz.svg",
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    capital: "Bishkek",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/lao.svg",
    name: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    capital: "Vientiane",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/lva.svg",
    name: "Latvia",
    alpha2Code: "LV",
    capital: "Riga",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/lbn.svg",
    name: "Lebanon",
    alpha2Code: "LB",
    capital: "Beirut",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/lso.svg",
    name: "Lesotho",
    alpha2Code: "LS",
    capital: "Maseru",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/lbr.svg",
    name: "Liberia",
    alpha2Code: "LR",
    capital: "Monrovia",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/lby.svg",
    name: "Libya",
    alpha2Code: "LY",
    capital: "Tripoli",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/lie.svg",
    name: "Liechtenstein",
    alpha2Code: "LI",
    capital: "Vaduz",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/ltu.svg",
    name: "Lithuania",
    alpha2Code: "LT",
    capital: "Vilnius",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/lux.svg",
    name: "Luxembourg",
    alpha2Code: "LU",
    capital: "Luxembourg",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/mac.svg",
    name: "Macao",
    alpha2Code: "MO",
    capital: "",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mkd.svg",
    name: "Macedonia (the former Yugoslav Republic of)",
    alpha2Code: "MK",
    capital: "Skopje",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/mdg.svg",
    name: "Madagascar",
    alpha2Code: "MG",
    capital: "Antananarivo",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/mwi.svg",
    name: "Malawi",
    alpha2Code: "MW",
    capital: "Lilongwe",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/mys.svg",
    name: "Malaysia",
    alpha2Code: "MY",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mdv.svg",
    name: "Maldives",
    alpha2Code: "MV",
    capital: "Malé",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mli.svg",
    name: "Mali",
    alpha2Code: "ML",
    capital: "Bamako",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/mlt.svg",
    name: "Malta",
    alpha2Code: "MT",
    capital: "Valletta",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/mhl.svg",
    name: "Marshall Islands",
    alpha2Code: "MH",
    capital: "Majuro",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/mtq.svg",
    name: "Martinique",
    alpha2Code: "MQ",
    capital: "Fort-de-France",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/mrt.svg",
    name: "Mauritania",
    alpha2Code: "MR",
    capital: "Nouakchott",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/mus.svg",
    name: "Mauritius",
    alpha2Code: "MU",
    capital: "Port Louis",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/myt.svg",
    name: "Mayotte",
    alpha2Code: "YT",
    capital: "Mamoudzou",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/mex.svg",
    name: "Mexico",
    alpha2Code: "MX",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/fsm.svg",
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    capital: "Palikir",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/mda.svg",
    name: "Moldova (Republic of)",
    alpha2Code: "MD",
    capital: "Chișinău",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/mco.svg",
    name: "Monaco",
    alpha2Code: "MC",
    capital: "Monaco",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/mng.svg",
    name: "Mongolia",
    alpha2Code: "MN",
    capital: "Ulan Bator",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mne.svg",
    name: "Montenegro",
    alpha2Code: "ME",
    capital: "Podgorica",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/msr.svg",
    name: "Montserrat",
    alpha2Code: "MS",
    capital: "Plymouth",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/mar.svg",
    name: "Morocco",
    alpha2Code: "MA",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/moz.svg",
    name: "Mozambique",
    alpha2Code: "MZ",
    capital: "Maputo",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/mmr.svg",
    name: "Myanmar",
    alpha2Code: "MM",
    capital: "Naypyidaw",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/nam.svg",
    name: "Namibia",
    alpha2Code: "NA",
    capital: "Windhoek",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/nru.svg",
    name: "Nauru",
    alpha2Code: "NR",
    capital: "Yaren",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/npl.svg",
    name: "Nepal",
    alpha2Code: "NP",
    capital: "Kathmandu",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/nld.svg",
    name: "Netherlands",
    alpha2Code: "NL",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/ncl.svg",
    name: "New Caledonia",
    alpha2Code: "NC",
    capital: "Nouméa",
    region: "Oceania",
    subregion: "Melanesia",
  },
  {
    flag: "https://restcountries.eu/data/nzl.svg",
    name: "New Zealand",
    alpha2Code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/nic.svg",
    name: "Nicaragua",
    alpha2Code: "NI",
    capital: "Managua",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/ner.svg",
    name: "Niger",
    alpha2Code: "NE",
    capital: "Niamey",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/nga.svg",
    name: "Nigeria",
    alpha2Code: "NG",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/niu.svg",
    name: "Niue",
    alpha2Code: "NU",
    capital: "Alofi",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/nfk.svg",
    name: "Norfolk Island",
    alpha2Code: "NF",
    capital: "Kingston",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/prk.svg",
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    capital: "Pyongyang",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mnp.svg",
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    capital: "Saipan",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/nor.svg",
    name: "Norway",
    alpha2Code: "NO",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/omn.svg",
    name: "Oman",
    alpha2Code: "OM",
    capital: "Muscat",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/pak.svg",
    name: "Pakistan",
    alpha2Code: "PK",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/plw.svg",
    name: "Palau",
    alpha2Code: "PW",
    capital: "Ngerulmud",
    region: "Oceania",
    subregion: "Micronesia",
  },
  {
    flag: "https://restcountries.eu/data/pse.svg",
    name: "Palestine, State of",
    alpha2Code: "PS",
    capital: "Ramallah",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/pan.svg",
    name: "Panama",
    alpha2Code: "PA",
    capital: "Panama City",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/png.svg",
    name: "Papua New Guinea",
    alpha2Code: "PG",
    capital: "Port Moresby",
    region: "Oceania",
    subregion: "Melanesia",
  },
  {
    flag: "https://restcountries.eu/data/pry.svg",
    name: "Paraguay",
    alpha2Code: "PY",
    capital: "Asunción",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/per.svg",
    name: "Peru",
    alpha2Code: "PE",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/phl.svg",
    name: "Philippines",
    alpha2Code: "PH",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/pcn.svg",
    name: "Pitcairn",
    alpha2Code: "PN",
    capital: "Adamstown",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/pol.svg",
    name: "Poland",
    alpha2Code: "PL",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/prt.svg",
    name: "Portugal",
    alpha2Code: "PT",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/pri.svg",
    name: "Puerto Rico",
    alpha2Code: "PR",
    capital: "San Juan",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/qat.svg",
    name: "Qatar",
    alpha2Code: "QA",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/kos.svg",
    name: "Republic of Kosovo",
    alpha2Code: "XK",
    capital: "Pristina",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/reu.svg",
    name: "Réunion",
    alpha2Code: "RE",
    capital: "Saint-Denis",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/rou.svg",
    name: "Romania",
    alpha2Code: "RO",
    capital: "Bucharest",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/rus.svg",
    name: "Russian Federation",
    alpha2Code: "RU",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/rwa.svg",
    name: "Rwanda",
    alpha2Code: "RW",
    capital: "Kigali",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/blm.svg",
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    capital: "Gustavia",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/shn.svg",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    capital: "Jamestown",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/kna.svg",
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    capital: "Basseterre",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/lca.svg",
    name: "Saint Lucia",
    alpha2Code: "LC",
    capital: "Castries",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/maf.svg",
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    capital: "Marigot",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/spm.svg",
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    capital: "Saint-Pierre",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/vct.svg",
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    capital: "Kingstown",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/wsm.svg",
    name: "Samoa",
    alpha2Code: "WS",
    capital: "Apia",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/smr.svg",
    name: "San Marino",
    alpha2Code: "SM",
    capital: "City of San Marino",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/stp.svg",
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    capital: "São Tomé",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/sau.svg",
    name: "Saudi Arabia",
    alpha2Code: "SA",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/sen.svg",
    name: "Senegal",
    alpha2Code: "SN",
    capital: "Dakar",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/srb.svg",
    name: "Serbia",
    alpha2Code: "RS",
    capital: "Belgrade",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/syc.svg",
    name: "Seychelles",
    alpha2Code: "SC",
    capital: "Victoria",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/sle.svg",
    name: "Sierra Leone",
    alpha2Code: "SL",
    capital: "Freetown",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/sgp.svg",
    name: "Singapore",
    alpha2Code: "SG",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/sxm.svg",
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    capital: "Philipsburg",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/svk.svg",
    name: "Slovakia",
    alpha2Code: "SK",
    capital: "Bratislava",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/svn.svg",
    name: "Slovenia",
    alpha2Code: "SI",
    capital: "Ljubljana",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/slb.svg",
    name: "Solomon Islands",
    alpha2Code: "SB",
    capital: "Honiara",
    region: "Oceania",
    subregion: "Melanesia",
  },
  {
    flag: "https://restcountries.eu/data/som.svg",
    name: "Somalia",
    alpha2Code: "SO",
    capital: "Mogadishu",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/zaf.svg",
    name: "South Africa",
    alpha2Code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/sgs.svg",
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    capital: "King Edward Point",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/kor.svg",
    name: "Korea (Republic of)",
    alpha2Code: "KR",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/ssd.svg",
    name: "South Sudan",
    alpha2Code: "SS",
    capital: "Juba",
    region: "Africa",
    subregion: "Middle Africa",
  },
  {
    flag: "https://restcountries.eu/data/esp.svg",
    name: "Spain",
    alpha2Code: "ES",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
  },
  {
    flag: "https://restcountries.eu/data/lka.svg",
    name: "Sri Lanka",
    alpha2Code: "LK",
    capital: "Colombo",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/sdn.svg",
    name: "Sudan",
    alpha2Code: "SD",
    capital: "Khartoum",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/sur.svg",
    name: "Suriname",
    alpha2Code: "SR",
    capital: "Paramaribo",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/sjm.svg",
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    capital: "Longyearbyen",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/swz.svg",
    name: "Swaziland",
    alpha2Code: "SZ",
    capital: "Lobamba",
    region: "Africa",
    subregion: "Southern Africa",
  },
  {
    flag: "https://restcountries.eu/data/swe.svg",
    name: "Sweden",
    alpha2Code: "SE",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/che.svg",
    name: "Switzerland",
    alpha2Code: "CH",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
  },
  {
    flag: "https://restcountries.eu/data/syr.svg",
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    capital: "Damascus",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/twn.svg",
    name: "Taiwan",
    alpha2Code: "TW",
    capital: "Taipei",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/tjk.svg",
    name: "Tajikistan",
    alpha2Code: "TJ",
    capital: "Dushanbe",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/tza.svg",
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/tha.svg",
    name: "Thailand",
    alpha2Code: "TH",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/tls.svg",
    name: "Timor-Leste",
    alpha2Code: "TL",
    capital: "Dili",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/tgo.svg",
    name: "Togo",
    alpha2Code: "TG",
    capital: "Lomé",
    region: "Africa",
    subregion: "Western Africa",
  },
  {
    flag: "https://restcountries.eu/data/tkl.svg",
    name: "Tokelau",
    alpha2Code: "TK",
    capital: "Fakaofo",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/ton.svg",
    name: "Tonga",
    alpha2Code: "TO",
    capital: "Nuku'alofa",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/tto.svg",
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    capital: "Port of Spain",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/tun.svg",
    name: "Tunisia",
    alpha2Code: "TN",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/tur.svg",
    name: "Turkey",
    alpha2Code: "TR",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/tkm.svg",
    name: "Turkmenistan",
    alpha2Code: "TM",
    capital: "Ashgabat",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/tca.svg",
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    capital: "Cockburn Town",
    region: "Americas",
    subregion: "Caribbean",
  },
  {
    flag: "https://restcountries.eu/data/tuv.svg",
    name: "Tuvalu",
    alpha2Code: "TV",
    capital: "Funafuti",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/uga.svg",
    name: "Uganda",
    alpha2Code: "UG",
    capital: "Kampala",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/ukr.svg",
    name: "Ukraine",
    alpha2Code: "UA",
    capital: "Kiev",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/are.svg",
    name: "United Arab Emirates",
    alpha2Code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/gbr.svg",
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
  },
  {
    flag: "https://restcountries.eu/data/usa.svg",
    name: "United States of America",
    alpha2Code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/ury.svg",
    name: "Uruguay",
    alpha2Code: "UY",
    capital: "Montevideo",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/uzb.svg",
    name: "Uzbekistan",
    alpha2Code: "UZ",
    capital: "Tashkent",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/vut.svg",
    name: "Vanuatu",
    alpha2Code: "VU",
    capital: "Port Vila",
    region: "Oceania",
    subregion: "Melanesia",
  },
  {
    flag: "https://restcountries.eu/data/ven.svg",
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    capital: "Caracas",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/vnm.svg",
    name: "Viet Nam",
    alpha2Code: "VN",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/wlf.svg",
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    capital: "Mata-Utu",
    region: "Oceania",
    subregion: "Polynesia",
  },
  {
    flag: "https://restcountries.eu/data/esh.svg",
    name: "Western Sahara",
    alpha2Code: "EH",
    capital: "El Aaiún",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/yem.svg",
    name: "Yemen",
    alpha2Code: "YE",
    capital: "Sana'a",
    region: "Asia",
    subregion: "Western Asia",
  },
  {
    flag: "https://restcountries.eu/data/zmb.svg",
    name: "Zambia",
    alpha2Code: "ZM",
    capital: "Lusaka",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/zwe.svg",
    name: "Zimbabwe",
    alpha2Code: "ZW",
    capital: "Harare",
    region: "Africa",
    subregion: "Eastern Africa",
  },
];

export default mock;
