const mock = [
  {
    flag: "https://restcountries.eu/data/usa.svg",
    name: "United States of America",
    alpha2Code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/can.svg",
    name: "Canada",
    alpha2Code: "CA",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/rus.svg",
    name: "Russian Federation",
    alpha2Code: "RU",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
  },
  {
    flag: "https://restcountries.eu/data/grl.svg",
    name: "Greenland",
    alpha2Code: "GL",
    capital: "Nuuk",
    region: "Americas",
    subregion: "Northern America",
  },
  {
    flag: "https://restcountries.eu/data/mng.svg",
    name: "Mongolia",
    alpha2Code: "MN",
    capital: "Ulan Bator",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/aus.svg",
    name: "Australia",
    alpha2Code: "AU",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
  },
  {
    flag: "https://restcountries.eu/data/bra.svg",
    name: "Brazil",
    alpha2Code: "BR",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
  },
  {
    flag: "https://restcountries.eu/data/mex.svg",
    name: "Mexico",
    alpha2Code: "MX",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
  },
  {
    flag: "https://restcountries.eu/data/chn.svg",
    name: "China",
    alpha2Code: "CN",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
  },
  {
    flag: "https://restcountries.eu/data/kaz.svg",
    name: "Kazakhstan",
    alpha2Code: "KZ",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
  },
  {
    flag: "https://restcountries.eu/data/lby.svg",
    name: "Libya",
    alpha2Code: "LY",
    capital: "Tripoli",
    region: "Africa",
    subregion: "Northern Africa",
  },
  {
    flag: "https://restcountries.eu/data/ind.svg",
    name: "India",
    alpha2Code: "IN",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
  },
  {
    flag: "https://restcountries.eu/data/mdg.svg",
    name: "Madagascar",
    alpha2Code: "MG",
    capital: "Antananarivo",
    region: "Africa",
    subregion: "Eastern Africa",
  },
  {
    flag: "https://restcountries.eu/data/sau.svg",
    name: "Saudi Arabia",
    alpha2Code: "SA",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
  },
];

export default mock;
